export const container: string;
export const wrapper: string;
export const wrapperChessboard: string;
export const wrapperFooter: string;
export const wrapperMoves: string;
export const wrapperOpponent: string;
export const wrapperPlayer: string;
export const wrapperQuit: string;
export const wrapperText: string;
