name: Node.js CI

on:
  push:
    paths-ignore:
      - '**/*.md'

jobs:
  build:
    name: "Build Star Wars Quiz application"
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Use Node.js ${{ matrix.node-version }}
        uses: actions/setup-node@v1
        with:
          node-version: 14.x
      - run: npm ci
      - run: npm run build --if-present
      - run: npm run test:cov
      - run: npm run lint
      - uses: actions/upload-artifact@v1
        name: Upload build as artifact
        if: always()
        with:
          name: swquiz-dist
          path: ./dist
  deploy-on-github-pages:
    name: "Deploy app to GitHub Pages from main branch source code"
    if: github.ref == 'refs/heads/main'
    needs: build
    runs-on: ubuntu-latest
    steps:
      - uses: actions/download-artifact@v2
        with:
          name: swquiz-dist
          path: ./dist
      - name: Deploy app as GitHub Pages
        uses: peaceiris/actions-gh-pages@v3.7.0-6
        if: ${{ github.event_name != 'pull_request' && always() }}
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: "./dist"
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          force_orphan: true
          keep_files: false