export const bishop: string;
export const capturedWrapper: string;
export const king: string;
export const knight: string;
export const opponent: string;
export const pawn: string;
export const player: string;
export const queen: string;
export const rook: string;
